### ISSUE TITLE
custom Golang version saved $GOROOT

### ISSUE THREAD

**Issue by Michionlion** [mccurdyc/neighbor#8]
After running `make setup` in the `colton/concurrent-testing` branch, the `go` command no longer works, since it is looking for a `$GOROOT` at `/home/mccurdyc/go-cover`. There may be some saved environment variables in the binary? Not sure where else this could have been introduced.

This should be reproduced by just moving/renaming `/home/mccurdyc/go-cover` or otherwise sanitizing your environment, then running `make setup && go version`.

**Comment by Michionlion** [comment]
A completely clean install avoids this, but I'm not sure why...

**Comment by mccurdyc** [comment]
ill try to reproduce with the steps you have provided above

**Comment by mccurdyc** [comment]
ahh but i bet `$GOROOT` is set in that binary when I build it. i will check

**Comment by mccurdyc** [comment]
This is no longer related to neighbor, but may be related to https://github.com/mccurdyc/go-cover
